baseURL = "/"
languageCode = "en"
title = "Hinny Wass Yoga"
theme = "hugo-nuo"
enableRobotsTXT = true
canonifyurls = true

# Google Analytics UA number
googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = ""

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Online Classes & Blog Posts"
  weight = 100
  identifier = "post"
  url = "/post"


#
#[[menu.main]]
#  name = "Class Schedule"
#  weight = 10
#  identifier = "class-schedule"
#  url = "/class-schedule"
#
#[[menu.main]]
#  name = "Forrest Yoga"
#  weight = 10
#  identifier = "forrest-yoga"
#  url = "/forrest-yoga"
#
#[[menu.main]]
#  name = "Private Lessons"
#  weight = 10
#  identifier = "private-lessons"
#  url = "/private-lessons"


# Add your own params here
[params]
  author = "Hinny Wass"
  avatar = "/images/logo.svg"
  seotitle = "Hinny Wass Yoga"
  subtitle = "Forrest Yoga is a strong and dynamic form of vinyasa yoga which is specifically designed to counteract the discomforts of modern life.  Hinny is Oxford's first Forrest Yoga teacher, and she offers public classes and private lessons."
  description = "Forrest Yoga is a strong and dynamic form of vinyasa yoga which is specifically designed to counteract the discomforts of modern life.  Hinny is Oxford's first Forrest Yoga teacher, and she offers public classes and private lessons."
  paginate = 10

  # Choose your social networks
  email = "hinny@hinnywassyoga.co.uk"
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

